---
- name: VMs Creation
  hosts: localhost
  connection: local

# last tested in 2018 on ESXi v6.x
  vars_prompt:
    - name: "vcenter_user"
      prompt: "Enter vcenter username"
      private: no
    - name: "vcenter_pass"
      prompt: "Enter vcenter password"
      private: yes
  tasks:
    - vsphere_guest:
        validate_certs: false
        vcenter_hostname: <vcenter fqdn hostname>
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        guest: "{{ item }}"
        state: present
        vm_extra_config:
          notes: notes
        vm_disk:
          disk1:
            size_gb: 25
            type: thin
            datastore: <datastore fqdn>
        vm_nic:
          nic1:
            type: vmxnet3
            network: <network name - vcentre specific>
            network_type: standard
        vm_hardware:
          memory_mb: 1024
          num_cpus: 1
          osid: centos64Guest #image name, must exist
          scsi: paravirtual
        esxi:
          datacenter: <ESXi specific DC ID>
          hostname: <esxi fqdn hostname>
      with_items:
        - VM01
        - VM02
        - VM03
